config:
  gcp:project: cr-lab-dstamer-2609192157
  urly-wurly:location: us-central1
  urly-wurly:branch: master
  urly-wurly:repository: https://bitbucket.org/cloudreach/urly-wurly
  urly-wurly:domain: w.crlabs.cloud
  urly-wurly:project_name: cr-lab-dstamer-2609192157
  urly-wurly:project_number: 456033566869
