config:
  gcp:project: cr-prod-urlywurly-1570435182
  urly-wurly:location: us-central1
  urly-wurly:branch: master
  urly-wurly:repository: bitbucket_cloudreach_urly-wurly
  urly-wurly:domain: cldr.ch
  urly-wurly:project_name: cr-prod-urlywurly-1570435182
  urly-wurly:project_number: 685700238968
  urly-wurly:verification-record-name: cldr.ch.
  urly-wurly:verification-record-data: google-site-verification=dXKVwXA0t4NI6JHx1y4NyRe6fdn-lHwYTN6IxRZh2ug
  urly-wurly:verification-record-type: TXT
